### ISSUE TITLE
External DVD

### ISSUE THREAD

**Issue by tikman** [DeltaResero/GC-Wii-Linux-Kernels#7]
Sorry, it just I'm new in just new in Linux, but I have a question? I was thinking, since the Wii (2009 new drive) or Wii U (Wii mode) can't read DVD video or read game disc (read iso file) anymore on linux because of new drive, can it read disc by using external DVD? By the way, I went to this two link pages (http://forum.wiibrew.org/read.php?29,68339,69270#msg-69270 and http://forum.wiibrew.org/read.php?29,61010) so it can read external DVD. The two link page I went before, do I need some tool like kernel or some stuff from the code to compile the Linux to run external DVD so it can read DVD instead of using the Wii or Wii U (Wii Mode) with new drive?

**Comment by DeltaResero** [comment]
You'll likely need to take a look at the MINI configuration and enable the relevant modules for external disc drives. It shouldn't be anything too extensive, I just don't recall what it is exactly that needs enabled for that, but it should be relatively easy to find.

---- On Thu, 16 Apr 2015 21:47:00 -0300 tikman &lt;notifications@github.com&gt; wrote ---- 

Sorry, it just I'm new in just new in Linux, but I have a question? I was thinking, since the Wii (2009 new drive) or Wii U (Wii mode) can't read DVD video or read game disc (read iso file) anymore on linux, can it read disc by using external DVD? By the way, I went to this two link pages (http://forum.wiibrew.org/read.php?29,68339,69270#msg-69270 and http://sourceforge.net/p/gc-linux/mailman/message/26476826/) so it can read external DVD. The two link page I went before, do I need some tool like kernel or some stuff from the code to compile the Linux to run external DVD so it can read DVD instead of using the Wii or Wii U (Wii Mode) with new drive?

**Comment by tikman** [comment]
Ohhh, OK, thanks man.

**Comment by tikman** [comment]
By the way, but I'm a bit confuse, is MINI configuration is same thing as kernel configuration?

**Comment by DeltaResero** [comment]
There is a MINI and an IOS option in the kernel configuration. Which every you choose will be the type of kernel that is built.

**Comment by tikman** [comment]
Ohhh I see. But there one more I thing I should ask you early, I went to the page (http://forum.wiibrew.org/read.php?29,61010) and got stuck and confuse on step 1 where its say "To fix this you have to recompile the kernel". And what does it mean

Start with the kernel configuration of your actual kernel image. To get your
kernel configuration just boot into your whiite linux installation and do a:

               "zcat /proc/config.gz > /tmp/my_kernel_config.txt"

This will create a file
named /tmp/my_kernel_config.txt, which you need to copy to your "build" machine

**Comment by tikman** [comment]
I almost forgot, I went to the guy's website and it got some steps, it saids:

To fix this you have to recompile the kernel:

Start with the kernel configuration of your actual kernel image. To get your
kernel configuration just boot into your whiite linux installation and do a:

                "zcat /proc/config.gz > /tmp/my_kernel_config.txt"

This will create a file
named /tmp/my_kernel_config.txt, which you need to copy to your "build" machine
(i.e. where you will build/compile your kernel).

Then follow the instructions at:

[www.gc-linux.org]

At step 2 of "Building the kernel image", instead of using a default config, do
copy the contents of your my_kernel_config.txt file to linux-2.6.32/.config .
Then modify the .config file to set the needed option (CONFIG_BLK_DEV_SR=y). The
.config file is a text file that you can manually edit. Alternatively, if you
prefer it, you can do a "make menuconfig" to tweak the options. 

I have a question, on step one what it says, what does it mean, To get your
kernel configuration just boot into your whiite linux installation ("zcat /proc/config.gz > /tmp/my_kernel_config.txt"), And this will create a file
named /tmp/my_kernel_config.txt, which you need to copy to your "build" machine
(i.e. where you will build/compile your kernel).

**Comment by tikman** [comment]
The first part you said early, "You'll likely need to take a look at the MINI configuration and enable the relevant modules for external disc drives". Does it means it don't have to be modified and I can used External DVD and run straight to Wii or Wii U
