### ISSUE TITLE
No video output

### ISSUE THREAD

**Issue by OatmealDome** [DeltaResero/GC-Wii-Linux-Kernels#9]
I compiled the kernel and copied the Wheezy filesystem image to /dev/disk1s2, but it seems that there is no video output to the TV screen. I can see the drive light flashing (presumably indicating SD card read/write activity?) and when typing the login credentials ("root[RETURN]delta[RETURN]") the drive light flashes each time I pressed return.

I then tried to start the Wi-Fi interface ("ifup wlan0") with the preconfigured /etc/network/interfaces file I added. But the Wii didn't appear as online in my router interface, respond to pings, or accept an ssh connection. This would be easier to troubleshoot if I could actually see the console output.

**Comment by DeltaResero** [comment]
Sorry about the late reply. Haven't looked at this in years due to post secondary. I'm hoping to replace the disc images at some point with an installer. Neagix is currently working on fixing the video output issue with more recent kernels. This repository has been a mess and on pause for the last few years, but I'm hoping to clean it once we get past the SDHC issue.
